### ISSUE TITLE
Propose change to bottom-level AddToQueue()

### ISSUE THREAD

**Issue by red-gum-tree** [Flosi23/rythm#3]
Since _index_ is already passed a default parameter from parent function on sending !play command, we can handle a "0 songs in _Songs_" condition as well as place a new song at the specified index properly with the following modifications:

`this.songs.splice((index <== 0) ? 0 : index, 0, ...songs);`

**Comment by simonwkla** [comment]
Sorry for responding to your proposal this late.. ;-;

The problem with your solution is, that it would not work out if the given index is longer than the array itself. 
The idea behind these few lines is the following
```ts
if (index >= this.songs.length - 1) {
   index = this.songs.length - 1 < 0 ? 0 : this.songs.length - 1;
}
```
Originally i just wanted to ensure that if the index is out of range is should just be set to `songs.length - 1`;
So i came up with this code
```ts
if (index >= this.songs.length){
   index = this.songs.length - 1;
}
```
The problem is: If `this.songs.length` is `0` then the index would be set to `-1`. In order to avoid that we need another if
statement checking if the current length is 0 and if that is the case then the index should just be set to 0.

And thats why the code now looks like this:

```ts
if (index >= this.songs.length - 1) {
   index = this.songs.length - 1 < 0 ? 0 : this.songs.length - 1;
}
```
Though with your comment you did point out another issue I didnt think of before. If the index is less than 0 it should be set to 0. If we implement this code too it now looks like this:

```ts
if (index < 0) {
    index = 0;
}

if (index >= this.songs.length) {
    index = this.songs.length - 1 < 0 ? 0 : this.songs.length - 1;
}
```
Now this code should work now matter what index is given. Please point it out if there are any better ways to this, for now I will implement this.

**Comment by simonwkla** [comment]
I had a look at the js docs and saw that the check whether the given index is higher than the array length is not necesarry since `array.splice` deals with this issue. So your proposal is a 100% correct and will be implemented.
